### ISSUE TITLE
Application segfaults often

### ISSUE THREAD

**Issue by z3ntu** [fulhax/ncpamixer#21]
1. Every time when exiting the application with "Esc"
```
Thread 1 "ncpamixer" received signal SIGSEGV, Segmentation fault.
0x0000aaaac0dbdf70 in Pa::deletePaobjects (this=0xaaaac0dea070 <pa>, objects=0xaaaac0dea078 <pa+8>) at /home/user/ncpamixer/src/pa.cpp:203
203             delete i->second;
(gdb) bt
#0  0x0000aaaac0dbdf70 in Pa::deletePaobjects (this=0xaaaac0dea070 <pa>, objects=0xaaaac0dea078 <pa+8>) at /home/user/ncpamixer/src/pa.cpp:203
#1  0x0000aaaac0dbd90c in Pa::clearAllPaObjects (this=0xaaaac0dea070 <pa>) at /home/user/ncpamixer/src/pa.cpp:40
#2  0x0000aaaac0dbd878 in Pa::~Pa (this=0xaaaac0dea070 <pa>, __in_chrg=<optimized out>) at /home/user/ncpamixer/src/pa.cpp:29
#3  0x0000ffffa80ea4b8 in __funcs_on_exit () from /lib/ld-musl-aarch64.so.1
#4  0x0000ffffa80e28e0 in exit () from /lib/ld-musl-aarch64.so.1
#5  0x0000ffffa80e9cb8 in __libc_start_main () from /lib/ld-musl-aarch64.so.1
#6  0x0000aaaac0dbb52c in _start_c (p=<optimized out>) at crt/crt1.c:17
#7  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
2. Randomly when navigation through the UI
e.g.
```
0x0000aaaaac90ba94 in Pa::remove_paobject(std::map<unsigned int, PaObject*, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, PaObject*> > >*, unsigned int) ()
(gdb) bt
#0  0x0000aaaaac90ba94 in Pa::remove_paobject(std::map<unsigned int, PaObject*, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, PaObject*> > >*, unsigned int) ()
#1  0x0000ffffa8d12af4 in ?? () from /usr/lib/libpulse.so.0
#2  0x0000ffffa8a8d900 in pa_pdispatch_run () from /usr/lib/pulseaudio/libpulsecommon-12.2.so
#3  0x0000ffffa8cf3f68 in ?? () from /usr/lib/libpulse.so.0
#4  0x0000ffffa8a903c4 in ?? () from /usr/lib/pulseaudio/libpulsecommon-12.2.so
#5  0x0000ffffa8a9274c in ?? () from /usr/lib/pulseaudio/libpulsecommon-12.2.so
#6  0x0000ffffa8a92a60 in ?? () from /usr/lib/pulseaudio/libpulsecommon-12.2.so
#7  0x0000ffffa8a931a8 in ?? () from /usr/lib/pulseaudio/libpulsecommon-12.2.so
#8  0x0000ffffa8d06908 in pa_mainloop_dispatch () from /usr/lib/libpulse.so.0
#9  0x0000ffffa8d06a28 in pa_mainloop_iterate () from /usr/lib/libpulse.so.0
#10 0x0000ffffa8d06a84 in pa_mainloop_run () from /usr/lib/libpulse.so.0
#11 0x0000ffffa8d12dd8 in ?? () from /usr/lib/libpulse.so.0
#12 0x0000ffffa8a9fde4 in ?? () from /usr/lib/pulseaudio/libpulsecommon-12.2.so
#13 0x0000ffffa8d90670 in ?? () from /lib/ld-musl-aarch64.so.1
#14 0x0000ffffa8859ad0 in ?? ()
#15 0x910063e1d28010e8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by c0r73x** [comment]
Yeah I've noticed this myself with the new version of pulse. I will check if I can fix it later today.
