### ISSUE TITLE
Assertion 'c' failed at pulse/context.c:1055, function void pa_context_disconnect(pa_context *)(). Aborting.

### ISSUE THREAD

**Issue by yurivict** [fulhax/ncpamixer#61]
ncpamixer fails at runtime:
```
W: [(null)] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
Assertion 'c' failed at pulse/context.c:1055, function void pa_context_disconnect(pa_context *)(). Aborting.
Abort trap
```

**Comment by SuperSandro2000** [comment]
> Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.

Is your pulseaudio compiled with libcap?

**Comment by yurivict** [comment]
I use ```pulseaudio-14.2``` and it doesn't have the string ```libcap``` anywhere in the source tree.

**Comment by SuperSandro2000** [comment]
pulseaudio isn't compiled with capabilities support https://cgit.freebsd.org/ports/tree/audio/pulseaudio/Makefile#n45

https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/stable-14.x/configure.ac#L644-655

**Comment by yurivict** [comment]
pcap can't be enabled in PulseAudio on FreeBSD because PulseAudio uses non-POSIX header ```sys/capability.h```, see https://bugs.freedesktop.org/show_bug.cgi?id=72580

I remember that previous versions of ncpamixer worked fine on FreeBSD. Does it really need libpcap support in PulseAudio?

**Comment by SuperSandro2000** [comment]
It may be that I followed a false flag. The caps warning is only a warning and may or may not have something to do with this https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/stable-14.x/src/daemon/caps.c#L95-97

**Comment by yurivict** [comment]
The problem is this fatal assertion in pulseaudio:
```
Starting program: /usr/local/bin/ncpamixer
[New LWP 196947 of process 62859]
[Detaching after fork from child process 62875]
W: [] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
[New LWP 196969 of process 62859]
Assertion 'c' failed at ../src/pulse/context.c:1076, function void pa_context_disconnect(pa_context *)(). Aborting.

Thread 1 received signal SIGABRT, Aborted.
Sent by thr_kill() from pid 62859 and user 1001.
thr_kill () at thr_kill.S:4
4       RSYSCALL(thr_kill)
(gdb) bt
#0  thr_kill () at thr_kill.S:4
#1  0x000000002c1c9d34 in __raise (s=s@entry=6) at /disk-samsung/freebsd-src/lib/libc/gen/raise.c:50
#2  0x000000002c27dce9 in abort () at /disk-samsung/freebsd-src/lib/libc/stdlib/abort.c:64
#3  0x000000002bf364e4 in pa_context_disconnect () from /usr/local/lib/libpulse.so.0
#4  0x000000000021830b in Pa::pa_connect (this=0x2334d0 <pulse>) at /usr/ports/audio/ncpamixer/work/ncpamixer-1.3.8/src/pa.cpp:101
#5  0x00000000002188d5 in Pa::init (this=0x2334d0 <pulse>) at /usr/ports/audio/ncpamixer/work/ncpamixer-1.3.8/src/pa.cpp:143
#6  0x0000000000214009 in main (argc=1, argv=0x7fffffffe648) at /usr/ports/audio/ncpamixer/work/ncpamixer-1.3.8/src/pulsemixer.cpp:110
(gdb)
```

**Comment by yurivict** [comment]
Somewhat related issue: https://github.com/fulhax/ncpamixer/issues/88
