### ISSUE TITLE
SIGSEGV when firefox play/pauses

### ISSUE THREAD

**Issue by JustCauseWhyNot** [fulhax/ncpamixer#65]
this is the output I get from gdb.
```Thread 2 "threaded-ml" received signal SIGSEGV, Segmentation fault.                                                                                                                          [Switching to Thread 0x7ffff75606c0 (LWP 9905)]```

bt 
```#0  0x000000000040b96b in ?? ()
#1  0x00000000000014e5 in ?? ()
#2  0x00007fffec00fbd0 in ?? ()
#3  0x00007fffec018418 in ?? ()
#4  0xe415b14f671e6500 in ?? ()
#5  0x00007fffec00fbd0 in ?? ()
#6  0x0000000000420800 in ?? ()
#7  0x0000000000420810 in ?? ()
#8  0x000000000040ca8b in ?? ()
#9  0x000000000000002c in ?? ()
#10 0x00007fffec002a20 in ?? ()
#11 0x00007ffff755f950 in ?? ()
#12 0xe415b14f671e6500 in ?? ()
#13 0x0000000000000002 in ?? ()
#14 0x00007fffec002a20 in ?? ()
#15 0x00007fffec009300 in ?? ()
#16 0x00007ffff755f950 in ?? ()
#17 0x0000000000000002 in ?? ()
#18 0x00007ffff7eeb200 in ?? () from /usr/lib64/libpulse.so.0
#19 0x000000000000002c in ?? ()
#20 0x00007ffff7eeb40d in ?? () from /usr/lib64/libpulse.so.0
#21 0x00007ffff7a04a91 in ?? () from /usr/lib64/pulseaudio/libpulsecommon-16.1.so
#22 0x00007ffff7a04e1c in pa_pdispatch_run () from /usr/lib64/pulseaudio/libpulsecommon-16.1.so
#23 0x00007ffff7edff6e in ?? () from /usr/lib64/libpulse.so.0
#24 0x00007ffff7a077f3 in ?? () from /usr/lib64/pulseaudio/libpulsecommon-16.1.so
#25 0x00007ffff7a0a8ff in ?? () from /usr/lib64/pulseaudio/libpulsecommon-16.1.so
#26 0x00007ffff7ef6786 in pa_mainloop_dispatch () from /usr/lib64/libpulse.so.0
#27 0x00007ffff7ef6aa4 in pa_mainloop_iterate () from /usr/lib64/libpulse.so.0
#28 0x00007ffff7ef6b50 in pa_mainloop_run () from /usr/lib64/libpulse.so.0
#29 0x00007ffff7f05309 in ?? () from /usr/lib64/libpulse.so.0
#30 0x00007ffff7a1dcee in ?? () from /usr/lib64/pulseaudio/libpulsecommon-16.1.so
#31 0x00007ffff7b38ab3 in ?? () from /lib64/libc.so.6
#32 0x00007ffff7bbad2c in ?? () from /lib64/libc.so.6

**Comment by tricktux** [comment]
Is this still an issue? I cannot reproduce.

**Comment by JustCauseWhyNot** [comment]
Oh I'm not sure. I'm not using ncpamixer anyways due to this issue I believe. I'm currently using pavutcontrol-qt without issues.

**Comment by tricktux** [comment]
@c0r73x  Then it can probably be closed.
